version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - yum install -y maven
  pre_build:
    commands:
      - java --version
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -lsh
    finally:
      -  echo Vuild 